---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spegel-org
  namespace: flux-system
spec:
  interval: 15m
  type: oci
  url: oci://ghcr.io/spegel-org/helm-charts
