---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.cilium.yaml
  - helmrepository.postfinance.yaml
  - helmrepository.spegel-org.yaml
  - helmrepository.prometheus-community.yaml
