---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: flux-system
      interval: 15m
  values:
    providerRegex: |
      ^(${CLUSTER_NAME}-(control-plane|worker)-[0-9]+)$
    bypassDnsResolution: true
