---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: homelab
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - ExternalIP
          - LoadBalancerIP
      attributes:
        communities:
          standard: ["65535:65282"]
        localPreference: 100
      selector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ["never-used-value"]}
