---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dmz-free"
spec:
  blocks:
    - start: "172.16.5.10"
      stop: "172.16.5.200"
  serviceSelector:
    matchExpressions:
      - {key: ipam, operator: NotIn, values: [fixed]}
