[tools]
node = "lts"
"npm:markdownlint-cli2" = "latest"
"npm:markdownlint-sentences-per-line" = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
opentofu = "latest"
"pipx:ansible-core" = "latest"
sops = "latest"
