---
version: "3"
vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
env:
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"
includes:
  format: .taskfiles/format
  kubernetes: .taskfiles/kubernetes
  pre-commit: .taskfiles/pre-commit
  proxmox: .taskfiles/proxmox
  sops: .taskfiles/sops
tasks:
  default:
    silent: true
    cmd: task -l
