---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: v1.7.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 15m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: smallstep-certificates
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      host: longhorn.${CLUSTER_DOMAIN}
      tls: true
      tlsSecret: tls-longhorn-ingress-http
