---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: external-dns-internal
    sources:
      - service
      - ingress
      - traefik-proxy
    txtOwnerId: ${CLUSTER_NAME}
    domainFilters:
      - ${CLUSTER_DOMAIN}
      - ${CLUSTER_REVERSE_ZONE}.in-addr.arpa.
    provider:
      name: rfc2136
    extraArgs:
      - "--traefik-disable-legacy"
      - "--rfc2136-host=bind.dns.svc.cluster.local"
      - "--rfc2136-port=53"
      - "--rfc2136-create-ptr"
      - "--rfc2136-zone=${CLUSTER_DOMAIN}"
      - "--rfc2136-zone=${CLUSTER_REVERSE_ZONE}.in-addr.arpa"
      - "--rfc2136-tsig-keyname=tsig-key"
      - "--rfc2136-tsig-secret=${BIND_TSIG_KEY}"
      - "--rfc2136-tsig-secret-alg=${BIND_TSIG_ALGORITHM}"
