---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 15m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # -- Providers
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    # -- Enable IngressRoute
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "Host(`traefik.${CLUSTER_DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
        entryPoints: [websecure]
        tls:
          secretName: tls-traefik-dashboard-ingress-http
    globalArguments:
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
    additionalArguments:
      - --serversTransport.insecureSkipVerify=true
      - --log.level=INFO
    ports:
      web:
        redirectTo:
          port: websecure
          priority: 10
          permanent: true
    service:
      annotations:
        lbipam.cilium.io/ips: ${CLUSTER_INGRESS_IP}
        lbipam.cilium.io/sharing-key: ingress.${CLUSTER_DOMAIN}
        external-dns.alpha.kubernetes.io/hostname: ingress.${CLUSTER_DOMAIN}
        lbipam.cilium.io/sharing-cross-namespace: ${CLUSTER_INGRESS_NAMESPACES}
      labels:
        ipam: fixed
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    extraObjects:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: tls-traefik-dashboard-ingress-http
          namespace: traefik
        spec:
          commonName: traefik.${CLUSTER_DOMAIN}
          secretName: tls-traefik-dashboard-ingress-http
          dnsNames:
            - traefik.${CLUSTER_DOMAIN}
          issuerRef:
            kind: ClusterIssuer
            name: smallstep-certificates
