---
version: "3"
tasks:
  init:
    desc: "Run 'terraform init'"
    dir: terraform/proxmox
    cmds:
      - terraform init --upgrade
  plan:
    desc: "Run 'terraform plan'"
    dir: terraform/proxmox
    cmds:
      - terraform plan
  apply:
    desc: "Run 'terraform apply'"
    dir: terraform/proxmox
    cmds:
      - terraform apply  -auto-approve
  output:
    desc: "Run 'terraform output'"
    dir: terraform/proxmox
    cmds:
      - terraform output -raw kubeconfig > ../../kubernetes/kubeconfig
      - terraform output -raw talosconfig > ../../kubernetes/talosconfig
