---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: spegel
      version: v0.0.28
      sourceRef:
        kind: HelmRepository
        name: spegel-org
        namespace: flux-system
      interval: 15m
  values:
    spegel:
      appendMirrors: true
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    service:
      registry:
        hostPort: 29999
    serviceMonitor:
      enabled: true
