---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: homelab
  CLUSTER_DOMAIN: homelab.molier.net
  CLUSTER_INGRESS_IP: 172.16.5.1
  CLUSTER_DNS_IP: 172.16.5.2
  CLUSTER_POSTGRES_IP: 172.16.5.3
  BGP_ROUTER_IP: 172.16.1.10
