---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:lkEthuhtijYj9XJH61d0kAOuJOBsZ6HDrJXIXvZQc63SWm8Xksc80H1ZxKf6zdPBPrXVFN8HojeWlgexmRyQMXNbcgELPXu1L0I=,iv:kRfJqzH0TGzkPnwY0QBCx9Q8NBC1gl16miQzegRSv2E=,tag:RDNCO8t05i8jyqNswwZkRA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1uyjwu3munqtxc3xvdvhtsd7d6cexjers3ed90h7wgw3j88xqa4esh2zqsl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Mk14TG5EUmRXWmNDOGZE
        ak40RlRYc1h0NnAwOFBzRDB0RFpjVkVsOWhrCm9tdFlOa2EzVkJyRzZaY0VRYnow
        c1ZVNC81R2svclBFUVltT3ZGd1FvQ1kKLS0tIFhybjdNRjNJT1pJMkRyMzgxaTBk
        NW41VzBCWGFiQkpSdVZUY1Z6QWM4YVkKuZwX8MMdO0hLSpUzjNZnsAyOTuXPTmcK
        ns6wssn/fP+Aj/L80wHyo0sLnB2Rpk+hxxn8yrjVxo1d2e0h/KWOyw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13etaa3cakur045vllvkl6npfnfrj47an2xfppvhznzdysv3eq5xsgmpwdd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdTB3NFVZV2Jod1V6VVpl
        cUMzVzZGcC9MbVZBWmthN1Y2NTBqYzR2S1E4CmlnRDRWUmFBbXR4R1p3YVRWUDVj
        NDJJRHRxRHpRdzg1QVdjeFRJVlQ2Um8KLS0tIGdOVmJQeDFFa2NNRE91N3JCcmpV
        cko2RERWRWxhTkRxK29jSExzRHFpTzAKUVXzfsK99x7SeICplB6rY5c891IDn9ug
        wb027TvUi163kR9FPJB2nthfSHR7+15c0paE6ec0LWDeFr/iHm96Gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age163mxng0aq62et853gfhty3z57j3cch8nrxmslmswza9z90wl9c8sjds0wy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUmhlclJYTVdoLzJUL00w
        RWNYeHpkRzJ0Kys1NU93L0hSUTl0TGdzWGlrCm12SCtBQzQ5UVNTT1VuZGEvVkJV
        d2c3cTl1cVRJZ3dJcUEzYVhIVDA0c28KLS0tIHNOSnJXUTlRTDYycUsyUVZmbzAr
        OEZORnRjSEFiVkcvTDluY3l5emszeEUK+ryNWTYDmvHQfTKXgh8ARM+2B6MCQgnG
        /2nASMLn2Dsyu1Sky+JxR7a0DbgynH8oWjjGvGFkMoFR84MdMx/VIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-30T15:10:40Z"
  mac: ENC[AES256_GCM,data:indjAzf0exMtV8fyMPDkjdgbRHqwKNSZtehSyO7vYTWP+Yuc/buIYBmkpmCe2NLctaP2zZJmwg+7fLEbeLuyUN40X2IvRM++q6ri1w25X0tF3+akQzNbcTZjkSXFYXLzTQ06DZPnfNOMJ3EijKz+28Qr9B4gobq/NMI/gB4/3ic=,iv:xTqPHuzjJ98owAuca+HdvZ9Oh8XfA4F5tJsOe/ykCOw=,tag:uJFH7FYAMXqgABagAqlvmg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
