---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
  - helmrelease.certificates.yaml
configMapGenerator:
  - name: certificates-helm-values
    namespace: smallstep
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
