---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bind
  namespace: dns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 101
    controllers:
      bind:
        containers:
          bind:
            image:
              repository: ghcr.io/remkomolier/bind
              tag: 9.18.27@sha256:6eed12c305e0a0544a7a59a4858884a6f1aaed342e6d7c1e69fb9f4610f53275
            args:
              - -c
              - /etc/bind/named.conf
              - -g
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      bind:
        annotations:
          lbipam.cilium.io/ips: ${CLUSTER_INGRESS_IP}
          lbipam.cilium.io/sharing-key: ingress.${CLUSTER_DOMAIN}
          external-dns.alpha.kubernetes.io/hostname: ns.${CLUSTER_DOMAIN}
          lbipam.cilium.io/sharing-cross-namespace: ${CLUSTER_INGRESS_NAMESPACES}
        labels:
          ipam: fixed
        controller: bind
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
            targetPort: 9053
          dns-udp:
            port: 53
            protocol: UDP
            targetPort: 9053
    persistence:
      config:
        type: configMap
        name: bind-config
        globalMounts:
          - path: /etc/bind/named.conf
            subPath: named.conf
            readOnly: true
          - path: /var/bind/pri/${CLUSTER_DOMAIN}.zone
            subPath: cluster.zone
            readOnly: true
          - path: /var/bind/pri/${CLUSTER_REVERSE_ZONE}.in-addr.arpa.zone
            subPath: cluster-reverse.zone
            readOnly: true
      secrets:
        type: secret
        name: bind-secrets
        globalMounts:
          - path: /etc/bind/tsig.key
            subPath: tsig.key
            readOnly: true
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/bind
    secrets:
      secrets:
        enabled: true
        stringData:
          tsig.key: |
            key "tsig-key" {
                algorithm ${BIND_TSIG_ALGORITHM};
                secret "${BIND_TSIG_KEY}";
            };
    configMaps:
      config:
        enabled: true
        data:
          named.conf: |
            include "/etc/bind/tsig.key";

            options {
                directory "/var/bind";

                listen-on {
                    none;
                };

                listen-on port 9053 {
                    any;
                };

                listen-on-v6 {
                    none;
                };

                allow-transfer {
                    none;
                };

                pid-file "/var/run/named/named.pid";

                allow-recursion {
                    none;
                };
                recursion no;
            };

            zone "${CLUSTER_DOMAIN}" {
                type master;
                file "pri/${CLUSTER_DOMAIN}.zone";
                allow-transfer {
                    key tsig-key;
                };
                update-policy {
                    grant tsig-key zonesub ANY;
                };
            };

            zone "${CLUSTER_REVERSE_ZONE}.in-addr.arpa" {
                type master;
                file "pri/${CLUSTER_REVERSE_ZONE}.in-addr.arpa.zone";
                allow-transfer {
                    key rndc-key;
                };
                update-policy {
                    grant tsig-key zonesub ANY;
                };
            };
          cluster.zone: |
            $TTL 1m
            @           IN      SOA   ns.${CLUSTER_DOMAIN}. noc.${CLUSTER_DOMAIN}.  (
                                                            20240913180001; serial
                                                            5m            ; refresh
                                                            1m            ; retry
                                                            1w            ; expire
                                                            1m            ; minimum
                                                            )
            @           IN      NS    ns
            ns    1w    IN      A     ${CLUSTER_INGRESS_IP}
          cluster-reverse.zone: |
            $TTL 1m
            @           IN      SOA   ns.${CLUSTER_DOMAIN}. noc.${CLUSTER_DOMAIN}.  (
                                                            20240913180001; serial
                                                            5m            ; refresh
                                                            1m            ; retry
                                                            1w            ; expire
                                                            1m            ; minimum
                                                            )
            ${CLUSTER_REVERSE_INGRESS_IP}     1w    IN      PTR   ns.${CLUSTER_DOMAIN}.
