---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system-cilium-config
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./kubernetes/infrastructure/kube-system/cilium/config
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: kube-system-cilium-app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
