---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
  - kustomization.kube-system-cilium-app.yaml
  - kustomization.kube-system-cilium-config.yaml
