---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: cilium-helm-values
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: smallstep-certificates
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - hubble.${CLUSTER_DOMAIN}
          tls:
            - secretName: tls-cilium-hubble-ingress-tls
              hosts:
                - hubble.${CLUSTER_DOMAIN}
