---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: fifo
resources:
  - helmrelease.cilium.yaml
configMapGenerator:
  - name: cilium-helm-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
