---
name: Build and publish a container image
on:
  workflow_dispatch:
    inputs:
      container:
        description: "Container to build"
        required: true
jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: |
            .github
            containers/${{ github.event.inputs.container }}
      - name: Inspect Dockerfile
        id: inspection
        uses: ./.github/actions/inspect-dockerfile
        with:
          dockerfile: ./containers/${{ github.event.inputs.container }}/Dockerfile
          prefix: ${{ github.event.inputs.container }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
      - name: Login to Github Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: |
            ghcr.io/${{github.repository_owner}}/${{ github.event.inputs.container }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}},value=${{ steps.inspection.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.inspection.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.inspection.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.container }}
            org.opencontainers.image.source=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.url=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.version=${{ steps.inspection.outputs.version }}
            ${{ steps.inspection.outputs.labels }}
          annotations: |
            org.opencontainers.image.title=${{ github.event.inputs.container }}
            org.opencontainers.image.source=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.url=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.version=${{ steps.inspection.outputs.version }}
            ${{ steps.inspection.outputs.labels }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          platforms: linux/arm64,linux/amd64
          context: ./containers/${{ github.event.inputs.container }}/
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
