---
name: Build and publish a container image
on:
  workflow_dispatch:
    inputs:
      container:
        description: "Container to build"
        required: true
jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            containers/${{ github.event.inputs.container }}
      - name: Inspect Dockerfile
        id: inspection
        uses: ./.github/actions/inspect-dockerfile
        with:
          dockerfile: ./containers/${{ github.event.inputs.container }}/Dockerfile
          prefix: ${{ github.event.inputs.container }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: |
            ghcr.io/${{github.repository_owner}}/${{ github.event.inputs.container }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}},value=${{ steps.inspection.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.inspection.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.inspection.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.inputs.container }}
            org.opencontainers.image.source=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.url=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.version=${{ steps.inspection.outputs.version }}
            ${{ steps.inspection.outputs.labels }}
          annotations: |
            org.opencontainers.image.title=${{ github.event.inputs.container }}
            org.opencontainers.image.source=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.url=http://github.com/${{github.repository}}/containers/${{ github.event.inputs.container }}
            org.opencontainers.image.version=${{ steps.inspection.outputs.version }}
            ${{ steps.inspection.outputs.labels }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64,linux/amd64
          context: ./containers/${{ github.event.inputs.container }}/
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          annotations: ${{ steps.metadata.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
