name: Pull Request Completed

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

permissions: read-all

jobs:
  trunk-annotate:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
        with:
          post-annotations: true
